spring.application.name=Fspringproject

spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/embed?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.hikari.username=root
spring.datasource.hikari.password=sh365199!
spring.datasource.hikari.connection-test-query=SELECT 1+1 FROM dual

mybatis.configuration.map-underscore-to-camel-case=true
spring.mvc.throw-exception-if-no-handler-found=true  
spring.resources.add-mappings=false  
spring.mvc.static-path-pattern=/static/**
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=org.embed.dto
